name: lister
description: "A simple reorderable list in Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.0+4

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.7.5
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

